name: CI
on: [push, pull_request]
jobs:
  check:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Check out code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Run tests and lint
      run: make ci
